### ISSUE TITLE
No Matches for kind "TriggerAuthentication" in version "keda.k8s.io/v1alpha1"

### ISSUE THREAD

**Issue by juneldnerosa23** [kedacore/sample-dotnet-worker-servicebus-queue#11]
I'm following the steps from [here](https://github.com/kedacore/sample-dotnet-worker-servicebus-queue), and I encountered an error when deploying the autoscaler. 

This is the command where I encountered the issue.
kubectl apply -f .\deploy\deploy-autoscaling.yaml --namespace keda-dotnet-sample

The error was `error: unable to recognize "deploy-autoscaling.yaml": no matches for kind "TriggerAuthentication" in version "keda.k8s.io/v1alpha1"`

**Comment by juneldnerosa23** [comment]
What did I missed from the installation ?

**Comment by tomkerkhove** [comment]
What version of KEDA do you have?

**Comment by juneldnerosa23** [comment]
I think I'm running keda version 1.0.0
![image](https://user-images.githubusercontent.com/37841816/69349772-50a6a800-0cb3-11ea-9315-fbaf40054884.png)

**Comment by juneldnerosa23** [comment]
I just follow your instructions here.
https://github.com/kedacore/sample-dotnet-worker-servicebus-queue

**Comment by tomkerkhove** [comment]
Installation of KEDA is not covered, it's just a [**Pre-Requisites**](https://github.com/kedacore/sample-dotnet-worker-servicebus-queue#pre-requisites).

Hm how did you install KEDA? It's best to just use Helm https://keda.sh/deploy/#deploying-with-helm

Can you please check:
- What image version of KEDA you are running
- What CRDs are installed
- Have a look at the KEDA installation

I did the run-through today and it worked fine.

**Comment by juneldnerosa23** [comment]
Thank you, I will try it now. I will update you how it goes.

**Comment by juneldnerosa23** [comment]
I execute this command.
- helm install keda kedacore/keda --namespace keda

then it returns error.
"Error: could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server could not find the requested resource"

**Comment by juneldnerosa23** [comment]
I'm using helm 3.0

**Comment by tomkerkhove** [comment]
What Kubernetes version are you using?

**Comment by juneldnerosa23** [comment]
I'm using v1.13.12

**Comment by tomkerkhove** [comment]
It feels like that might be it. Checking this and will document it. https://github.com/kedacore/keda-docs/issues/49

Sorry about that..

**Comment by juneldnerosa23** [comment]
Okay, I just save this link https://github.com/kedacore/keda-docs/issues/49.

**Comment by juneldnerosa23** [comment]
based on this https://github.com/kedacore/sample-dotnet-worker-servicebus-queue/issues/11#issuecomment-557144927.

when you do the run through as you said, what version of helm, kubernetes & keda are you using?

**Comment by juneldnerosa23** [comment]
It works now :) I just run the command `kubectl api-resources` and the kind: TriggerAuthentication works.

**Comment by tomkerkhove** [comment]
Hm interesting, so the CRD was not created then? 🤔 

Not sure how that happend - You just ran the current KEDA code without Helm or guidance from keda.sh/deploy, is that a good summary? In other words, how can we improve :)

**Comment by juneldnerosa23** [comment]
I deployed the crds with these commands. am i right?

kubectl create namespace keda
kubectl apply -f deploy/crds/keda.k8s.io_scaledobjects_crd.yaml
kubectl apply -f deploy/crds/keda.k8s.io_triggerauthentications_crd.yaml
kubectl apply -f deploy/

**Comment by tomkerkhove** [comment]
Adding @ahmelsayed as FYI in case there is an issue.

I think we can close this issue though, ok for you?

**Comment by juneldnerosa23** [comment]
Yes, Thank you.

**Comment by markusdresch** [comment]
i got the same issue (keda-2.0.0-rc), but only in one cluster, others work fine. installed using `kubectl -f git...`
> unable to recognize "xxx.yaml": no matches for kind "TriggerAuthentication" in version "keda.k8s.io/v1alpha1"

it's strange, because `kubectl api-resources` does list triggerauthentication. same for scaledobjects.

**Comment by zroubalik** [comment]
Please note that apiVersion has been changed from `keda.k8s.io` to `keda.sh`. Please change that in your Scaledobjects and TA resources

**Comment by tomkerkhove** [comment]
We have changed the namespace of the CRD, I will update the sample asap.

See our migration guide on KEDA.sh for more info.

**Comment by markusdresch** [comment]
that was it. thanks.
