### ISSUE TITLE
KEDA scaler for Azure Service Bus in Private End Point not working

### ISSUE THREAD

**Issue by ubhanja** [kedacore/sample-dotnet-worker-servicebus-queue#25]
KEDA scaler is working with AKS public cluster with Azure Service Bus triggered scale. But when we use a private cluster and Azure service bus within that , we get below error from KEDA scaledObject and PODS are not scaled.

2021-09-24T09:47:37.242Z ERROR azure_servicebus_scaler error {"error": "error code: 401, Details: claim is empty or token is invalid. TrackingId:713a0ea4-ae27-4a64-b0c1-c2f76b36e5ee_G1, SystemTracker:msautomationreporthub.servicebus.windows.net:messagegenerator, Timestamp:2021-09-24T09:47:37"}

[temp.txt](https://github.com/kedacore/sample-dotnet-worker-servicebus-queue/files/7225258/temp.txt)

Do we need to make any changes in setting in Azure service bus? Please advise.
Attached is the `Yaml```

**Comment by tomkerkhove** [comment]
Can you add your configuration please?

**Comment by tomkerkhove** [comment]
Oh the temp.txt is the config.

**Comment by tomkerkhove** [comment]
I don't know if we support private endpoints though, it's best to open an issue on the main repo

**Comment by ubhanja** [comment]
ok Let me open it in main repo

**Comment by ubhanja** [comment]
@tomkerkhove Do you know what could be the probable issue with azure_servicebus_scaler error {"error": "error code: 401, Details: claim is empty or token is invalid. TrackingId:713a0ea4-ae27-4a64-b0c1-c2f76b36e5ee_G1. We tried making the Azure service Bus public ,but getting the same error. Only difference is we are running it in K8s private cluster. @tomkerkhove what is the link to main repo?

**Comment by tomkerkhove** [comment]
Main repo is on https://github.com/kedacore/keda

I was recently talking to somebody who was using private clusters and was able to scale them, but I'm not sure if it was @Ritikaa96 or not?
