### ISSUE TITLE
Support for  Service Bus queues with Sessions Enabled

### ISSUE THREAD

**Issue by ssathasivan** [kedacore/sample-dotnet-worker-servicebus-queue#26]
Thanks for this queue worker. Is this tested with Service Bus queues with Sessions Enabled . We have some queues with SessionEnabled to ensure that messages are processed in order.
Currently message processing is handled by azure functions,  however the processes are long running . So are worried about function time outs. Wanted to check the possibility of using this worker and still ensure that ordered processing happens

**Comment by tomkerkhove** [comment]
Sorry, I'm not sure what your question is - Is it if it works with sessions? If so, I recommend giving it a try but I'm not sure.
