### ISSUE TITLE
Can we have filters on types of service bus messages which should be triggered by KEDA

### ISSUE THREAD

**Issue by vishalsharmaeic** [kedacore/sample-dotnet-worker-servicebus-queue#28]
We have a service bus queue that has two types of messages in the queue, and I want to restrict the triggering of instances if the service bus message is of certain type.

I can attach metadata if it is supported through that path..

Any help here. ?

**Comment by tomkerkhove** [comment]
Unfortunately not, we only scale based on queue metrics and not on the message level since we do not know. We do support this, though, if you would use a topic instead as you can autoscale based on the topics.
