### ISSUE TITLE
Authentication issue when trying to process orders

### ISSUE THREAD

**Issue by rkralston** [kedacore/sample-dotnet-worker-servicebus-queue#8]
I have everything set up. I run the order generator. I can see the messages hitting the queue. Nothing happens in AKS.

When I look at the k8s tool in Code, the order-processor has a red dot next to it. I'm not sure what to do from there.

I noticed in the YAML that it is pulling the image from your Docker account?

Should I package that in a new container and deploy the image to my ACR?

**Comment by tomkerkhove** [comment]
The service bus connection string does not seem to be valid anymore, can you verify that?

**Comment by tomkerkhove** [comment]
The generator uses send permissions while the message pump uses receive permission. So that is not a guarantee, can you pleasure generate a new one with these permissions please?

**Comment by rkralston** [comment]
Quotes or no quotes around the connection strong on the command line? You example has quotes.

**Comment by rkralston** [comment]
Getting the same result with new key.

**Comment by tomkerkhove** [comment]
Are you sure that the generated base64 representation is correct? (ie no trailing spaces)

The error clearly indicates that it's an authentication issue when trying to start processing the messages

**Comment by rkralston** [comment]
I'm copying it using the portal copy function. 

I've tried to stand the Processor up locally, from the command line, outside Docker. I can't get that to run. I keep getting JSON error.

**Comment by tomkerkhove** [comment]
Are you creating the subscription on the queue itself or the namespace? I presume you've verified that you have Receive/Manage permissions?

Does it work in [Service Bus Explorer](https://github.com/paolosalvatori/ServiceBusExplorer)?

**Comment by rkralston** [comment]
On the queue. 

Not sure what you mean by verify. I looked at both subscriptions and they both have manage.

I'll try service bus explorer tomorrow.

**Comment by tomkerkhove** [comment]
Hi @rkralston, did you manage to test this? If so, did you get it working?

**Comment by rkralston** [comment]
No. We abandoned KEDA b/c it is considered experimental by MS.

**Comment by tomkerkhove** [comment]
That's fair. For what it's worth, that might change soon.

**Comment by rkralston** [comment]
Please let me know if it does.i am very excited about keda. I think it is a total game changer.

If I had bandwidth, this would be my open source project of choice.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jakobehn** [comment]
Keda went GA back in november, and is ready for production usage:
https://cloudblogs.microsoft.com/opensource/2019/11/19/keda-1-0-release-kubernetes-based-event-driven-autoscaling/

**Comment by jakobehn** [comment]
For what it's worth, I had this exact error when running a Docker container on my local machine that (at the time) had an incorrect system time. Clock mismatch makes the SAS token validation go nuts. After manually setting the correct time on my host, the problem went away

**Comment by johnknoop** [comment]
I'm getting this despite having the _correct_ time on my docker host 😕

**Comment by tomkerkhove** [comment]
Good to hear and sorry for the issues, unfortunately there's not much I can do about it..

**Comment by crgarcia12** [comment]
I just had the same situation. Restarting docker worked
